### ISSUE TITLE
Opencart 2.2

### ISSUE THREAD

**Issue by andreiwd** [gerencianet/gn-api-opencart#2]
Boa Noite amigos da GN.

Estou integrando o módulo da gerencianet na minha loja com plataforma Opencart 2.2 porém, estou tendo alguns probleminhas na finalização do pedido. Veja só os pequenos, mas graves, problemas encontrados:

Problema 1 - Numa Compra de 61,29, ao selecionar a forma de pagamento tenho as opções:

--- Boleto: R$61,29 (mas o boleto gerado é R$61,28) - Sumiu 0,01 daqui.

--- Cartão de Crédito: R$61,00 (cadê os R$0,29 daqui ?)

Problema 2 - Numa compra de R$60,00 onde foi utilizado um cupom de desconto de R$5,00, o módulo exibe: 
---- Gerar Boleto: R$55,00 (Mas o boleto gerado é de R$60,00 ou seja o módulo não calculou o cupom de desconto)

E tenho também uma outra questão:
Gostaria que aparecesse somente o logo no topo do boleto e não o texto com endereço e tudo mais ou somente o boleto sem personalização. não tem onde "setar" isso.

**Comment by jpferreira123** [comment]
Olá @andreiwd ,

Você poderia disponibilizar um link para que eu possa realizar uma compra de teste e verificar o erro? Caso tenha interesse, me adicione no skype: joao.ferreira.gerencianet ou abra um ticket através de sua conta Gerencianet com as informações.

Aguardo seu retorno.

**Comment by andreiwd** [comment]
Olá @jpferreira123, obrigado pelo retorno.

http://www.docelembrancinha.com.br/comprar/index.php 
(deve-se usar o index.php no final pois o dominio está com redirecionamento)

Eu abri um ticket lá na GN tb, mas não sabia qual responderia primeiro... rs.

Abraço!
