### ISSUE TITLE
Erro no plugin

### ISSUE THREAD

**Issue by ofelipecohen** [gerencianet/gn-api-opencart#3]
Instalei em meu OC 2.1.0.1 e quando tento configurar para que apareça somente boleto bancário, aparece o seguinte erro:

Notice: Undefined index: gerencianet_payment_option_card in /home/thecrows/public_html/sub/admin/controller/payment/gerencianet.php on line 39Warning: Cannot modify header information - headers already sent by (output started at /home/thecrows/public_html/sub/admin/index.php:84) in /home/thecrows/public_html/sub/system/storage/modification/system/library/response.php on line 12

Se eu selecionar boleto e cartão, fica normal.
Além disso, quando o cliente selecionar o método da GerenciaNet, é redirecionado para uma página com o estilo da minha HOME, ou seja, aparecem os banners e destaques que eu configurei para a página inicial do site, e somente abaixo as infos de pagamento.

Como corrigir?
Obrigado!

**Comment by jpferreira123** [comment]
Bom dia @ofelipecohen , tudo bem?

O problema já está sendo analisado e em breve será disponibilizado uma atualização de correção.

Caso tenha interesse, adicione no skype: joao.ferreira.gerencianet

**Comment by jpferreira123** [comment]
Bom dia @ofelipecohen ,

Uma nova atualização para o OpenCart está disponível. Por favor, remova seu módulo da Gerencianet instalado e inicie o processo de instalação novamente.

Caso o erro persista, entre em contato. Aguardo seu retorno.

**Comment by ofelipecohen** [comment]
Obrigado, JpFerreira!

Tentei outra vez, mas deu outro erro:

Warning: require(/home/thecrows/public_html/sub/lib/gerencianet/symfony/polyfill-mbstring/bootstrap.php): failed to open stream: No such file or directory in /home/thecrows/public_html/sub/lib/gerencianet/composer/autoload_real.php on line 55
Fatal error: require(): Failed opening required '/home/thecrows/public_html/sub/lib/gerencianet/symfony/polyfill-mbstring/bootstrap.php' (include_path='.:/usr/local/lib/php') in/home/thecrows/public_html/sub/lib/gerencianet/composer/autoload_real.php on line 55

O que seria? :/

---

De: jpferreira123 notifications@github.com
Enviado: terça-feira, 24 de maio de 2016 10:05
Para: gerencianet/gn-api-opencart
Cc: ofelipecohen; Mention
Assunto: Re: [gerencianet/gn-api-opencart] Erro no plugin (#3)

Bom dia @ofelipecohenhttps://github.com/ofelipecohen ,

Uma nova atualização para o OpenCart está disponível. Por favor, remova seu módulo da Gerencianet instalado e inicie o processo de instalação novamente.

Caso o erro persista, entre em contato. Aguardo seu retorno.

##

**Comment by jpferreira123** [comment]
Olá @ofelipecohen ,

Aparentemente é algum problema com a estrutura de pastas, mas eu precisaria acessar a página para analisar o problema com mais detalhes.. É possível? Podemos ter uma conversa mais rápida via skype? Caso não seja possível por skype, pode me repassar o link através do email **joao.ferreira@gerencianet.com.br**.

Muito Obrigado.
